name: Setup Magento Store

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  compute_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.supported-version.outputs.matrix }}
    steps:
      - uses: graycoreio/github-actions-magento2/supported-version@main
        id: supported-version
      - run: echo ${{ steps.supported-version.outputs.matrix }}

  setup-magento-extension:
    runs-on: ubuntu-latest
    needs: compute_matrix
    strategy:
      matrix: ${{ fromJSON(needs.compute_matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: graycoreio/github-actions-magento2/setup-magento@main
        with:
          composer_version: ${{ matrix.composer }}
          php_version: ${{ matrix.php }}
          magento_version: ${{ matrix.magento }}
          composer_auth: ${{ secrets.COMPOSER_AUTH }}
          package_name: "run_as_root/magento2-prometheus-exporter:@dev"
          source_folder: $GITHUB_WORKSPACE
      - run: composer config repositories.local path $GITHUB_WORKSPACE
        name: Add Github Repo for Testing
        working-directory: ${{ steps.setup-magento.outputs.path }}
        shell: bash
