name: Unit Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  compute_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.supported-version.outputs.matrix }}
    steps:
      - uses: graycoreio/github-actions-magento2/supported-version@main
        id: supported-version
      - run: echo ${{ steps.supported-version.outputs.matrix }}

  setup-magento-extension:
    runs-on: ubuntu-latest
    needs: compute_matrix
    strategy:
      matrix: ${{ fromJSON(needs.compute_matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: graycoreio/github-actions-magento2/setup-magento@main
        with:
          php-version: ${{ matrix.php }}
          magento_version: ${{ matrix.magento }}
          mode: extension
          coverage: xDebug
          apply_fixes: 'true'

      - run: cat $GITHUB_OUTPUT
      - run: ls -lah ${{ steps.setup-magento-get-magento-path.outputs.path }}
      - run: ls -lah ../magento2

      - run: ls -lah && composer --working-dir=${{ steps.setup-magento-get-magento-path.outputs.path }} require "run_as_root/magento2-prometheus-exporter:@dev" --no-update && composer install
        name: Require and attempt install
        working-directory:  ${{ inputs.magento_directory }}
        shell: bash
        env:
          COMPOSER_CACHE_DIR: ${{ steps.composer-cache.outputs.dir }}

      - run: php ${{ steps.setup-magento-get-magento-path.outputs.path }}/vendor/bin/phpunit -c dev/tests/unit/phpunit.xml.dist
        name: Run Unit Tests