name: Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  compute_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.supported-version.outputs.matrix }}
    steps:
      - uses: graycoreio/github-actions-magento2/supported-version@main
        id: supported-version
      - run: echo ${{ steps.supported-version.outputs.matrix }}

  setup-magento-extension:
    runs-on: ubuntu-latest
    needs: compute_matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.compute_matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - uses: graycoreio/github-actions-magento2/setup-magento@main
        id: setup-magento
        with:
          php-version: ${{ matrix.php }}
          magento_version: ${{ matrix.magento }}
          mode: extension
          coverage: xDebug
          apply_fixes: true

      - run: |
          composer install
          composer require "run-as-root/magento2-prometheus-exporter:@dev"
        name: Require and attempt install
        working-directory:  ${{ steps.setup-magento.outputs.path }}
        shell: bash
        env:
          COMPOSER_CACHE_DIR: ${{ steps.composer-cache.outputs.dir }}

      - uses: ./.github/dependency-checker
        with:
          php_version: ${{ matrix.php }}
          module_path: ${{ steps.setup-magento.outputs.path }}/vendor/run-as-root/magento2-prometheus-exporter/
          magento_root: ${{ steps.setup-magento.outputs.path }}

      - run: php ./vendor/bin/phpunit ./vendor/run-as-root/magento2-prometheus-exporter/Test/Unit
        working-directory:  ${{ steps.setup-magento.outputs.path }}
        name: Run Unit Tests
