name: Setup Magento Store

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  setup-magento-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./setup-magento
        with:
          php-version: 8.1
          tools: composer:v2
          mode: extension
          magento_version: 2.4.5-p1

      - run: composer config repositories.local path $GITHUB_WORKSPACE
        name: Add Github Repo for Testing
        working-directory: ${{ steps.setup-magento.outputs.path }}
        shell: bash

      - run: composer require my/package "@dev"
        name: Attempt install
        working-directory: ${{ steps.setup-magento.outputs.path }}
        shell: bash
        env:
          COMPOSER_AUTH: ${{ secrets.composer_auth }}